---
- name: Install samba
  apt:
    name: samba
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
  tags: samba

- name: Remove "sambashare" group (auto-added during samba package install)
  group:
    name: sambashare
    state: absent
  tags: samba

- name: Write samba configuration
  template:
    src: "templates/smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    owner: root
    group: root
    mode: 0644
  tags: samba

- name: Ensure samba share paths exist
  file: path={{ item.path }} state=directory mode={{ item.dirmask|default('0755') }} owner={{ samba_share_user }} group={{ samba_share_group }}
  with_items: "{{ samba_shares }}"
  tags: samba

- name: Restart samba
  systemd:
    name: smbd
    state: restarted
    daemon_reload: yes
  tags: samba
